import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Providers } from "./provider";
import ClientWrapper from "@/components/ClientWrapper";
import { ToastContainer, toast } from 'react-toastify';





const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "GetMeAChai",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Providers>
          <ClientWrapper className={`${geistSans.variable} ${geistMono.variable}`}>
            <div className="min-h-screen w-full bg-[#000000] bg-[radial-gradient(#ffffff33_1px,#00091d_1px)] bg-[size:20px_20px]">
              <ToastContainer/>
              <Navbar />
              <main className="min-h-[78vh] text-white">{children}</main>
              <Footer />
            </div>
          </ClientWrapper>
        </Providers>
      </body>
    </html>
  );
}
